#!/bin/fish

set response (jc upower -d | jq -r '.[0].detail | (.percentage | round | tostring) + " " + .state')
set charge (echo $response | awk '{print $1}')
set charging (echo $response | awk '{print $2}')

if test $charging = "charging"
    echo "󱐌 $charge%"
else if test $charging = "fully-charged"
    echo "   $charge%"
else
    if test $charge -ge "80"
        echo "   $charge%"
    else if test $charge -ge "60"
        echo "   $charge%"
    else if test $charge -ge "40"
        echo "   $charge%"
    else if test $charge -ge "20"
        echo "   $charge%"
    else if test $charge -ge "0"
        echo "   $charge%"
    end
end

